modLoader="javafml" 
loaderVersion="[39,)" 
license="MIT"

issuetrackerURL = "https://github.com/CaptainHottub/MachineMod/issues"

[[mods]]
modId="machinemod" 
version="1.0" 
displayName="Machine Mod" 
logoFile="logo.png" 
credits=""
authors="CaptainHottub" 

description='''
A mod with blocks I want.
'''
